stages:
  - package
  - build  
  - deploy

Package_staging:
  image: node
  stage: package
  script:
    - echo "$PACKAGE_FILE_STAGING" > package.json
    - ls
    - npm install --force
  artifacts:
    expire_in: 1 week
    paths: 
      - node_modules      
  only:
    - master

Build_staging:
  image: node
  stage: build
  script:
    - echo "$ENV_FILE_STAGING" > .env
    - echo "$CONFIG_FILE_STAGING" > nuxt.config.js
    # - echo "$PACKAGE_FILE_STAGING" > package.json
    - ls
    # - npm install --force
    - npm run build --standalone
  artifacts:
    expire_in: 1 week
    paths: 
      - .env
      - .nuxt
      - static
      - nuxt.config.js
      - package.json
  only:
    - master 
     
Deploy_staging:
  image: alpine
  stage: deploy
  script:
    - apk add --no-cache rsync openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_dsa
    - chmod 600 ~/.ssh/id_dsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - rsync -rav --delete .nuxt/ tamannaorange@67.227.213.5:~/np-service.tamanna.orangebd.com/.nuxt
    - rsync -rav  static/ tamannaorange@67.227.213.5:~/np-service.tamanna.orangebd.com/static
    - rsync  nuxt.config.js tamannaorange@67.227.213.5:~/np-service.tamanna.orangebd.com/   
    - rsync  package.json tamannaorange@67.227.213.5:~/np-service.tamanna.orangebd.com/
    - ssh tamannaorange@67.227.213.5 "cd ~/np-service.tamanna.orangebd.com && rm -f package-lock.json && npm install --force && pm2 restart eService && exit "
  environment:
    name: production
    url: https://np-service.tamanna.orangebd.com
  only:
    - master
